version: '3.4'

services:
  sm-games-be:
    image: sm-games-be
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
